import { PlaybookContentSchema, type PlaybookContent } from "./mobilization-contracts";

export const DEMO_STAFFING_FACTOR = 3;
export const DEMO_UNSPECIFIED_CREW = 6;
export const DEMO_STAFFING_REVISION_NOTE =
  "Mo-requested 300-volunteer demo staffing revision: fixed crew ×3; unspecified crew set to 6.";

export type DemoStaffingRevisionOptions = {
  factor: 2 | 3;
  unspecifiedCrew: 12 | 18;
  revisionNote: string;
};

/** A distinct marker makes this intentional second revision independently idempotent. */
export function additionalDemoStaffingRevisionNote(factor: 2 | 3): string {
  if (factor !== 2 && factor !== 3)
    throw new Error("The additional demo staffing factor must be 2 or 3.");
  return `Mo-requested additional 300-volunteer demo staffing revision: current fixed crew ×${factor}; unspecified crew set to ${DEMO_UNSPECIFIED_CREW * factor}.`;
}

const GUIDANCE_PREFIX = "300-volunteer DEMO planning baseline: ";
const GUIDANCE_SUFFIX =
  " people for this action or related safe assessment/support work. " +
  "Scale up for workload; use qualified, on-duty crew only; report shortages. " +
  "This is not a certified clinical or security staffing ratio.";
const guidanceFor = (people: number) => `${GUIDANCE_PREFIX}${people}${GUIDANCE_SUFFIX}`;
const escapePattern = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** Remove only exact, standalone blocks generated by this helper, never edited human guidance. */
function withoutOwnedGuidance(guidance: string, source: string): string {
  const ownsEarlierRevision = [DEMO_STAFFING_REVISION_NOTE,
    additionalDemoStaffingRevisionNote(2), additionalDemoStaffingRevisionNote(3)]
    .some((note) => source.includes(note));
  if (!ownsEarlierRevision) return guidance;
  const pattern = new RegExp(`${escapePattern(GUIDANCE_PREFIX)}([1-9][0-9]{0,2})${escapePattern(GUIDANCE_SUFFIX)}`, "g");
  const ranges: [number, number][] = [];
  for (const match of guidance.matchAll(pattern)) {
    const start = match.index;
    const end = start + match[0].length;
    if (Number(match[1]) > 500 ||
      (start > 0 && guidance.slice(start - 2, start) !== "\n\n") ||
      (end < guidance.length && guidance.slice(end, end + 2) !== "\n\n")) continue;
    const range: [number, number] = start > 0
      ? [start - 2, end]
      : [start, end < guidance.length ? end + 2 : end];
    const previous = ranges.at(-1);
    if (previous && previous[1] >= range[0]) {
      previous[1] = Math.max(previous[1], range[1]);
      if (previous[0] === 0 && guidance.slice(previous[1], previous[1] + 2) === "\n\n")
        previous[1] += 2;
    } else ranges.push(range);
  }
  let preserved = guidance;
  for (const [start, end] of ranges.reverse())
    preserved = preserved.slice(0, start) + preserved.slice(end);
  return preserved;
}

type StaffingChange = {
  actionId: string;
  title: string;
  before: number | null;
  after: number;
};

function appendWithinLimit(existing: string, addition: string, label: string): string {
  const combined = existing.length ? `${existing}\n\n${addition}` : addition;
  if (combined.length > 1000)
    throw new Error(`${label} would exceed 1000 characters; retain the original text and revise it explicitly.`);
  return combined;
}

/** A one-off, human-requested SOP revision; never a runtime multiplier on AI output. */
export function reviseDemoStaffing(content: PlaybookContent, options?: DemoStaffingRevisionOptions): {
  content: PlaybookContent;
  alreadyApplied: boolean;
  changes: StaffingChange[];
} {
  // Validate without using the parsed/trimmed copy: all unrelated human-authored text stays exact.
  PlaybookContentSchema.parse(content);
  if (options && (options.factor !== 2 && options.factor !== 3 ||
    options.unspecifiedCrew !== DEMO_UNSPECIFIED_CREW * options.factor))
    throw new Error("The additional staffing revision must use factor 2 with baseline 12, or factor 3 with baseline 18.");
  if (options && (typeof options.revisionNote !== "string" || !options.revisionNote.trim() ||
    options.revisionNote.length > 1000))
    throw new Error("A staffing revision needs a nonempty source marker of at most 1000 characters.");
  const factor = options?.factor ?? DEMO_STAFFING_FACTOR;
  const unspecifiedCrew = options?.unspecifiedCrew ?? DEMO_UNSPECIFIED_CREW;
  const revisionNote = options?.revisionNote ?? DEMO_STAFFING_REVISION_NOTE;
  const revised = structuredClone(content);
  if (content.source.includes(revisionNote))
    return { content: revised, alreadyApplied: true, changes: [] };

  const changes = revised.actions.map((action): StaffingChange => {
    const before = action.peopleNeeded;
    const after = before == null ? unspecifiedCrew : before * factor;
    if (after > 500)
      throw new Error(`Action ${action.id} would require ${after} people, exceeding the 500-person limit.`);
    action.peopleNeeded = after;
    const previousGuidance = options ? withoutOwnedGuidance(action.staffingGuidance, content.source) : action.staffingGuidance;
    action.staffingGuidance = appendWithinLimit(previousGuidance, guidanceFor(after), `Action ${action.id} staffing guidance`);
    return { actionId: action.id, title: action.title, before, after };
  });
  revised.source = appendWithinLimit(content.source, revisionNote, "Playbook source");
  PlaybookContentSchema.parse(revised);
  return { content: revised, alreadyApplied: false, changes };
}
