/**
 * Writes supabase/migrations/20261008210100_birrarung_marr_crew.sql: the zones placed on the site plan, every account in
 * supabase/crew.json (auth user, profile, description, certificates, when they're free) and the weekend's roster, as
 * plain SQL. Then `supabase db reset` (local) or `supabase db push` (the Spark) puts the whole crew up, no keys needed.
 *
 * People are matched by email, so a database that seed.ts already filled keeps its accounts, sign-ins and push tokens;
 * their details and where they stand are brought in line and the weekend's shifts are replaced, as roster.ts would.
 *
 *   bun scripts/gen-crew.ts 300 1 2026-10-10   (the crew the migration was made from)
 *   bun scripts/crew-sql.ts
 */
import { createHash } from 'node:crypto';

import { NODES, toLngLat, VENUE_ZONES } from '../src/data/venue';
import { localDay, localTime, makeShifts, roster, type RosterPerson } from '../src/lib/roster';
import type { TeamSlug } from '../src/lib/schema';

declare const Bun: { write(to: URL, text: string): Promise<number> };

type Skill = string | { skill: string; expires: string };
type CrewMember = {
  email: string; name: string; role: 'volunteer' | 'team_lead' | 'coordinator'; team: string | null; zone: string | null;
  skills?: Skill[]; languages?: string[]; phone?: string; bio?: string;
  experience?: 'first_timer' | 'returning';
  availability?: { said: string; windows: { from: string; to: string }[] };
};

const OUT = new URL('../supabase/migrations/20261008210100_birrarung_marr_crew.sql', import.meta.url);
// crew.json is gitignored: it's whatever gen-crew.ts last wrote.
const people = await import('../supabase/crew.json', { with: { type: 'json' } }).then((m) => m.default as CrewMember[])
  .catch(() => { throw new Error('No supabase/crew.json: run bun scripts/gen-crew.ts 300 1 2026-10-10 first'); });

const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replaceAll("'", "''")}'`);
const arr = (xs: string[]) => `'{${xs.map((x) => `"${x.replaceAll('"', '\\"')}"`).join(',')}}'`;
const rows = (xs: string[]) => xs.map((x) => `  (${x})`).join(',\n');
/** The same id for the same shift every time, so a regenerated file only differs where the roster does. */
const uuid = (key: string) => {
  const h = createHash('sha1').update(`moloop shift ${key}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
};

// ── the roster, as roster.ts makes it ──

const days = [...new Set(people.flatMap((m) => m.availability?.windows ?? []).map((w) => localDay(Date.parse(w.from))))].sort();
if (!days.length) throw new Error('Nobody has said when they are free: run bun scripts/gen-crew.ts first');
// A certificate that lapses before the weekend doesn't count.
const held = (m: CrewMember) => (m.skills ?? []).flatMap((s) =>
  typeof s === 'string' ? [s] : s.expires < days[0] ? [] : [s.skill]);
const rostered = people.filter((m) => m.role === 'volunteer' && m.team && m.availability?.windows.length);
const team: RosterPerson[] = rostered.map((m) => ({
  id: m.email.toLowerCase(), teamSlug: m.team as TeamSlug, skills: held(m), firstTimer: m.experience === 'first_timer',
  windows: m.availability!.windows.map((w) => ({ from: Date.parse(w.from), to: Date.parse(w.to) })),
}));
const shifts = makeShifts(days);
const { on, gaps } = roster(shifts, team);
const shiftId = new Map(shifts.map((s) => [s.id, uuid(`${s.teamSlug} ${s.startsAt}`)]));
const iso = (t: number) => new Date(t).toISOString();

// ── the SQL ──

const zones = Object.values(VENUE_ZONES).map((z) => {
  const [lng, lat] = toLngLat(NODES[z.node]);
  return `${q(z.slug)}, ${q(z.label)}, ${lat}, ${lng}`;
});
const members = people.map((m) => [
  q(m.email.toLowerCase()), q(m.name), q(m.role), q(m.team), q(m.zone), arr(m.languages ?? ['en']), q(m.phone), q(m.bio),
  q(m.experience), String(!!m.availability && m.role === 'volunteer'),
].join(', '));
const certs = people.flatMap((m) => (m.skills ?? []).map((s) => {
  const { skill, expires } = typeof s === 'string' ? { skill: s, expires: null } : s;
  return `${q(m.email.toLowerCase())}, ${q(skill)}, ${expires ? `${q(expires)}::date` : 'null'}`;
}));
const free = people.flatMap((m) => (m.availability?.windows ?? []).map((w) =>
  `${q(m.email.toLowerCase())}, ${q(w.from)}::timestamptz, ${q(w.to)}::timestamptz, ${q(m.availability!.said)}`));
const shiftRows = shifts.map((s) => `${q(shiftId.get(s.id)!)}::uuid, ${q(s.teamSlug)}, ${q(iso(s.startsAt))}::timestamptz, ` +
  `${q(iso(s.endsAt))}::timestamptz, ${s.need}, ${arr(s.requires)}::text[]`);
const onRows = shifts.flatMap((s) => on[s.id].map((email) => `${q(shiftId.get(s.id)!)}::uuid, ${q(email)}`));
const short = gaps.reduce((n, g) => n + g.short, 0);

const sql = `-- Generated by scripts/crew-sql.ts from supabase/crew.json; edit those, not this.
-- The festival crew: ${people.length} accounts (${people.filter((m) => m.role === 'volunteer').length} volunteers), their certificates and when they're free, and the
-- weekend's roster (${days.join(', ')}): ${shifts.length} shifts, ${onRows.length} places filled, ${short} short. People are matched by email, so
-- accounts seed.ts already made keep their ids, sign-ins and push tokens; the weekend's shifts are replaced.

-- ── zones, placed on the site plan (src/data/venue.ts) ──

update zones set name = z.name, lat = z.lat, lng = z.lng
from (values
${rows(zones)}
) as z(slug, name, lat, lng)
where zones.slug = z.slug;

-- ── who ──

create temporary table crew_seed (
  email text primary key, name text not null, role user_role not null, team text, zone text, languages text[] not null,
  phone text, bio text, experience text, rostered boolean not null
);
insert into crew_seed values
${rows(members)};

create temporary table crew_seed_skills (email text not null, skill text not null, expires_on date);
insert into crew_seed_skills values
${rows(certs)};

create temporary table crew_seed_free (email text not null, starts_at timestamptz not null, ends_at timestamptz not null, said text);
insert into crew_seed_free values
${rows(free)};

-- Sign in by email code, like an account the API made.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change
)
select '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', c.email, '', now(),
  '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', now(), now(), '', '', '', ''
from crew_seed c
where not exists (select 1 from auth.users u where lower(u.email) = c.email);

insert into auth.identities (provider_id, user_id, identity_data, provider, created_at, updated_at)
select u.id::text, u.id, jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true), 'email', now(), now()
from crew_seed c join auth.users u on lower(u.email) = c.email
on conflict (provider_id, provider) do nothing;

create temporary table crew_seed_ids as
select c.email, u.id from crew_seed c join auth.users u on lower(u.email) = c.email;

-- Volunteers with a roster start off shift: their shift puts them on duty. Everyone else is on now. Someone already
-- here keeps their status and where they were last seen.
insert into profiles (id, full_name, role, team_id, status, experience, languages, last_known_zone)
select i.id, c.name, c.role, t.id, (case when c.rostered then 'off_shift' else 'active' end)::volunteer_status,
  c.experience, c.languages, z.id
from crew_seed c
join crew_seed_ids i using (email)
left join teams t on t.slug = c.team
left join zones z on z.slug = c.zone
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, team_id = excluded.team_id,
  experience = excluded.experience, languages = excluded.languages, last_known_zone = excluded.last_known_zone;

insert into profile_private (id, phone, bio)
select i.id, c.phone, c.bio from crew_seed c join crew_seed_ids i using (email)
on conflict (id) do update set phone = coalesce(excluded.phone, profile_private.phone), bio = excluded.bio;

delete from volunteer_skills where volunteer_id in (select id from crew_seed_ids);
insert into volunteer_skills (volunteer_id, skill_id, expires_on)
select i.id, s.id, c.expires_on
from crew_seed_skills c join crew_seed_ids i using (email) join skills s on s.slug = c.skill;

delete from availability_windows where volunteer_id in (select id from crew_seed_ids);
insert into availability_windows (volunteer_id, starts_at, ends_at, raw_text)
select i.id, c.starts_at, c.ends_at, c.said from crew_seed_free c join crew_seed_ids i using (email);

-- ── the roster (src/lib/roster.ts) ──

create temporary table crew_seed_shifts (
  id uuid primary key, team text not null, starts_at timestamptz not null, ends_at timestamptz not null,
  need integer not null, requires text[] not null
);
insert into crew_seed_shifts values
${rows(shiftRows)};

create temporary table crew_seed_on (shift_id uuid not null, email text not null);
insert into crew_seed_on values
${rows(onRows)};

-- Replace the weekend's shifts; their assignments go with them.
delete from shifts where starts_at >= ${q(iso(localTime(days[0], 0)))} and starts_at < ${q(iso(localTime(days.at(-1)!, 24)))};

insert into shifts (id, team_id, starts_at, ends_at, required_count, required_skill_ids)
select s.id, t.id, s.starts_at, s.ends_at, s.need,
  coalesce((select array_agg(k.id order by r.ord) from unnest(s.requires) with ordinality as r(slug, ord)
    join skills k on k.slug = r.slug), '{}')
from crew_seed_shifts s join teams t on t.slug = s.team;

insert into shift_assignments (shift_id, volunteer_id)
select o.shift_id, i.id from crew_seed_on o join crew_seed_ids i using (email);

drop table crew_seed, crew_seed_skills, crew_seed_free, crew_seed_ids, crew_seed_shifts, crew_seed_on;
`;

await Bun.write(OUT, sql);
console.log(`${OUT.pathname.split('/').slice(-2).join('/')}: ${people.length} people, ${certs.length} certificates, ` +
  `${free.length} windows; ${shifts.length} shifts on ${days.join(' and ')}, ${onRows.length} filled, ${short} short`);
